//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastUsername
        {
            get
            {
                return ((string)(this["LastUsername"]));
            }
            set
            {
                this["LastUsername"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastPassword
        {
            get
            {
                return ((string)(this["LastPassword"]));
            }
            set
            {
                this["LastPassword"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastIPDB
        {
            get
            {
                return ((string)(this["LastIPDB"]));
            }
            set
            {
                this["LastIPDB"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RememberMe
        {
            get
            {
                return ((bool)(this["RememberMe"]));
            }
            set
            {
                this["RememberMe"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OfficialsForAll
        {
            get
            {
                return ((bool)(this["OfficialsForAll"]));
            }
            set
            {
                this["OfficialsForAll"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7001")]
        public int ApiPort
        {
            get
            {
                return ((int)(this["ApiPort"]));
            }
            set
            {
                this["ApiPort"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int SignalRPort
        {
            get
            {
                return ((int)(this["SignalRPort"]));
            }
            set
            {
                this["SignalRPort"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("27")]
        public int StartOfMonth
        {
            get
            {
                return ((int)(this["StartOfMonth"]));
            }
            set
            {
                this["StartOfMonth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("26")]
        public int EndOfMonth
        {
            get
            {
                return ((int)(this["EndOfMonth"]));
            }
            set
            {
                this["EndOfMonth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastUsernameDB
        {
            get
            {
                return ((string)(this["LastUsernameDB"]));
            }
            set
            {
                this["LastUsernameDB"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastPasswordDB
        {
            get
            {
                return ((string)(this["LastPasswordDB"]));
            }
            set
            {
                this["LastPasswordDB"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("User")]
        public string UserRole
        {
            get
            {
                return ((string)(this["UserRole"]));
            }
            set
            {
                this["UserRole"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string expDate
        {
            get
            {
                return ((string)(this["expDate"]));
            }
            set
            {
                this["expDate"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LateType
        {
            get
            {
                return ((int)(this["LateType"]));
            }
            set
            {
                this["LateType"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LateRepeat
        {
            get
            {
                return ((int)(this["LateRepeat"]));
            }
            set
            {
                this["LateRepeat"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal LateValue
        {
            get
            {
                return ((decimal)(this["LateValue"]));
            }
            set
            {
                this["LateValue"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dark")]
        public string ThemeName
        {
            get
            {
                return ((string)(this["ThemeName"]));
            }
            set
            {
                this["ThemeName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ChatBackgroundPath
        {
            get
            {
                return ((string)(this["ChatBackgroundPath"]));
            }
            set
            {
                this["ChatBackgroundPath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ar")]
        public string Language
        {
            get
            {
                return ((string)(this["Language"]));
            }
            set
            {
                this["Language"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Logo
        {
            get
            {
                return ((string)(this["Logo"]));
            }
            set
            {
                this["Logo"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#0047ab")]

        public global::System.String PrimaryColor
        {
            get
            {
                return ((global::System.String)(this["PrimaryColor"]));
            }
            set
            {
                this["PrimaryColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#0047ab")]

        public global::System.String MainColor
        {
            get
            {
                return ((global::System.String)(this["MainColor"]));
            }
            set
            {
                this["MainColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#0047ab")]
        public global::System.String SecondaryColor
        {
            get
            {
                return ((global::System.String)(this["SecondaryColor"]));
            }
            set
            {
                this["SecondaryColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#660503")]
        public global::System.String ThirdColorBrush
        {
            get
            {
                return ((global::System.String)(this["ThirdColorBrush"]));
            }
            set
            {
                this["ThirdColorBrush"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#ececec")]
        public global::System.String PrimaryColorBackground
        {
            get
            {
                return ((global::System.String)(this["PrimaryColorBackground"]));
            }
            set
            {
                this["PrimaryColorBackground"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#0047ab")]
        public global::System.String MainMenuColor
        {
            get
            {
                return ((global::System.String)(this["MainMenuColor"]));
            }
            set
            {
                this["MainMenuColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#0047ab")]
        public global::System.String PrimaryTextBrush
        {
            get
            {
                return ((global::System.String)(this["PrimaryTextBrush"]));
            }
            set
            {
                this["PrimaryTextBrush"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#37474F")]
        public global::System.String SecondaryTextBrush
        {
            get
            {
                return ((global::System.String)(this["SecondaryTextBrush"]));
            }
            set
            {
                this["SecondaryTextBrush"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#0097A7")]
        public global::System.String AccentColor
        {
            get
            {
                return ((global::System.String)(this["AccentColor"]));
            }
            set
            {
                this["AccentColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#004D56")]
        public global::System.String SidebarColor
        {
            get
            {
                return ((global::System.String)(this["SidebarColor"]));
            }
            set
            {
                this["SidebarColor"] = value;
            }
        }
    }
}
